### ISSUE TITLE
AuthMe should call the Login event after a successful session login.

### ISSUE THREAD

**Issue by sgdc3** [CryLegend/AuthMeBridge#2]
I think the scheduler to check the player status is useless, but we need to try first...

**Comment by CryLegend** [comment]
I'll look at it on a further rewrite

**Comment by CryLegend** [comment]
@sgdc3 When you have some free time, try if it works and if it does, commit it directly on the authme team repo

**Comment by sgdc3** [comment]
Already done on the authme repo ;)
