### ISSUE TITLE
AuthMeBridge as official addon

### ISSUE THREAD

**Issue by sgdc3** [CryLegend/AuthMeBridge#3]
@CryLegend would you like to join the authme development team and completely integrate AuthMeBridge into authme itself? ;)

**Comment by CryLegend** [comment]
@sgdc3 AuthMeBridge will probably never be integrated in AuthMe, because it can be compatible with others authentification plugins, althrough AuthMe the most used one.

**Comment by sgdc3** [comment]
the only other plugin is xAuth, we can keep compatibility without issues ;)

**Comment by CryLegend** [comment]
It already can be considered as an "official" add-on,  but my opinion is
that it's more easier to keep it as an add-on.
