### ISSUE TITLE
Problem with bungee

### ISSUE THREAD

**Issue by ghost** [CryLegend/AuthMeBridge#4]
Ok so i am using the Authme Reloaded 3.5 version for 1.9.
I am using the 1.5 for the 3.x version.
Login works the plugins works fine i have enable in the configs the hook with bungee all good
I get into the server i can use the commands that i have on the whitelist.I can't write/commands without loging in so far so good.But when i login i can move but i can't use any commands or write anything in the chat.Nothing will come up in the console is like everything the players is typing not reaching the consoles although players can move around freely.

**Comment by CryLegend** [comment]
Send me your BungeeCord config and BungeeAuthMeBridge config. Also please
check if AuthMeBridge is installed on bukkit side.

**Comment by Neverlookbackgrg** [comment]
ip_forward: false
network_compression_threshold: 256
stats: c40f7717-165b-4afc-94de-e2f14f1857e5
groups:
  md_5:
  - admin
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 127.0.0.1:35000
    restricted: false
timeout: 30000
player_limit: -1
listeners:
- query_port: 25625
  motd: '&1NeverCraft'
  priorities:
  - lobby
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: true
  host: 89.163.144.43:60000
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 45
  tab_size: 80
  ping_passthrough: false
  force_default_server: true
permissions:
  default:
  - bungeecord.command.list
  - bungeecord.command.alert
online_mode: false
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: -1


# List of servers which required to be authenticated
serversList:
  - lobby
# Allows or not commands to be performed if user is not logged in
commandsRequiresAuth: true
# List of commands allowed to be perform without being authenticated
commandsWhitelist:
  - /glist
# Allows or not user to talk in chat if he is not logged in
chatRequiresAuth: true
# Kick all players who switch servers without being authenticated (eg. plugin teleport)
# Do not set this option to true unless you know what you're doing!
serverSwitchRequiresAuth: true
# Enable session resume between servers (eg. autologin if you change server)
autoLogin: false


authmebridge
autoLoginMessage: §aYour session has been resumed by the bridge.

**Comment by ghost** [comment]
Download everything including all the files here

https://mega.nz/#fm/rZNmkZiD

**Comment by ghost** [comment]
forgot to include one of the files

**Comment by ghost** [comment]
any info on that?

**Comment by CryLegend** [comment]
Try the update

**Comment by ghost** [comment]
did you release a new update?

**Comment by ghost** [comment]
seems to work now thank you.

**Comment by CryLegend** [comment]
Yes I do

**Comment by ghost** [comment]
an another may bug i send my self to an another server inside bungee cord login in and then the server sents me back to my first server do we know why?
