### ISSUE TITLE
Issue register

### ISSUE THREAD

**Issue by Alibabaand40voleur** [CryLegend/AuthMeBridge#6]
When a player is new,
he need register in my server lobby, but when he change server, he need to re-register.

For player registred in all server, he get auto-login in all server, but for the new, is a probleme to register in all server.

I want him register in my server lobby and no more.

**Comment by CryLegend** [comment]
Hello,
The easiest way to do that is to use a MySQL database. I can help you if you want, contact me in PM. However, it has nothing to do here, because it is not an issue that comes my plugin.
Cordially
